### ISSUE TITLE
Invalidation Context

### ISSUE THREAD

**Issue by BayramInanc** [Jinya/WaterfallLayout#2]
Hi, when I test library with 30k+ image data, the scroll is smooth. However, when I use drag-drop, in drop case lag happens. I think, the reason is that the whole layout item calculation happens again. How to fix that?

**Comment by Jinya** [comment]
Sorry for the delayed reply. I guess the issue might be resolved by using a temporary snapshot of source cell view instead of the real cell view when handling drag and drop.

**Comment by BayramInanc** [comment]
> Sorry for the delayed reply. I guess the issue might be resolved by using a temporary snapshot of source cell view instead of the real cell view when handling drag and drop.

I think it is not possible with using apple drag-drop api???

**Comment by Jinya** [comment]
If you are only using drag and drop to display previews and transfer image copy to another independent view or application, I don't think there should be any issues with duplicate layout calculations. It would be helpful if you could share some code examples for us to further investigate.

If your goal is to use drag and drop for reordering cells with `WaterfallLayout`, it will undoubtedly involve a significant amount of computational work. My suggestion would be to avoid doing so. If you have a strong need for this functionality, you could try incorporating additional work within a custom layout.

**Comment by BayramInanc** [comment]
I think the problem can be solved by not calculating all items in all sections in prepare() method. Instead, we can calculate in func layoutAttributesForElements(in rect: [CGRect]) https://developer.apple.com/documentation/uikit/uicollectionviewlayout/1617769-layoutattributesforelements method. I remember, one guy said that if calculation process takes time, you should do this in this function
